JieCi = [
# relative spatial order
"above",
"against",
"along",
"among",
"amongst",
"around",
"aside",
"behind",
"below",
"beneath",
"beside",
"besides",
"downwards",
"into",
"inside",
"onto",
"outside",
"unto",
"under",
# relative temporal order
"during",
# relative logic
"except",
"despite",
"unlike",
"without",
"due",
"for",
"concerning",
"by",
"like",
# belonging
"of",
# co-existance condition
"with",
# (range) spatial or temporal oder
"across",
"after",
"afterwards",
"at",
"before",
"between",
"beyond",
"in",
"over",
"on",
"out",
"thorough",
"though",
"throug",
"through",
"throughout",
"til",
"up",
"toward",
"towards",
"until",
"upon",
"within",
# unclassified
"from",
"hither",
"to",
"about",
]

Determiner=[
"a",
"an",
"per",
"this",
"that",
"those",
"these",
"the",
"some",
"each",
"any",
]
DeterminerPersonal=[
"your",
"my",
"his",
"her",
"its",
"our",
"their",
"'s",
]

Modal=[
"can",
"could",
"must",
"may",
"might",
"shall",
"should",
"will",
"would",
]

AuxVerb=[
"be",
"is",
"are",
"was",
"were",
"have",
"has",
"had",
"do",
"does",
"did",
]

Adverb=[
"again",
"accordingly",
"actually",
"almost",
"already",
"alone",
"also",
"always",
"anyhow",
"anymore",
"anyway",
"anyways",
"apparently",
"approximately",
"away",
"awfully",
"beforehand",
"both",
"briefly",
"certainly",
"clearly",
"consequently",
"currently",
"definitely",
"enough",
"entirely",
"especially",
"ever",
"exactly",
"formerly",
"further",
"furthermore",
"hardly",
"hence",
"hereafter",
"hereby",
"herein",
"hereupon",
"hopefully",
"however",
"immediately",
"inasmuch",
"indeed",
"insofar",
"inward",
"just",
"largely",
"last",
"lately",
"latterly",
"likely",
"little",
"mainly",
"maybe",
"merely",
"moreover",
"most",
"mostly",
"much",
"namely",
"near",
"nearly",
"necessarily",
"never",
"nevertheless",
"no",
"nonetheless",
"normally",
"not",
"obviously",
"off",
"often",
"oftentimes", # added
"only",
"overall",
"particular",
"particularly",
"perhaps",
"poorly",
"possibly",
"potentially",
"predominantly",
"presumably",
"previously",
"primarily",
"probably",
"promptly",
"quickly",
"quite",
"rather",
"readily",
"really",
"reasonably",
"recently",
"relatively",
"respectively",
"same",
"seriously",
"significantly",
"similarly",
"slightly",
"so",
"somehow",
"sometime",
"sometimes",
"somewhat",
"somewhere",
"soon",
"specifically",
"still",
"strongly",
"substantially",
"successfully",
"such",
"sufficiently",
"sure",
"than",
"then",
"thence",
"thereafter",
"thereby",
"thoroughly",
"thouroughly",
"together",
"too",
"truly",
"unfortunately",
"unlikely",
"usefully",
"usually",
"very",
"well",
"whatever",
"widely",
]

PronounPerson=[
"you",
"I",
"he",
"she",
"it",
"they",
"him",
"her",
"them",
"we",
"us",
]

Conjunctive=[
"once",
"nor",
"neither",
"meanwhile",
"lest",
"instead",
"including",
"if",
"but",
"because",
"as",
"and",
"although",
"or",
"otherwise",
"since",
"whenever",
"unless",
"thus",
"therefore",
"therein",
"thereof",
"thereto",
"thereupon",
"plus",
"whereafter",
"whereas",
"whereby",
"wherein",
"whereupon",
"wherever",
"while",
"whoever",
"whomever",
"yet",
]

Questa=[
"how",
"what",
"when",
"whence",
"where",
"whether",
"which",
"whither",
"who",
"whom",
"whose",
"why",
]

Pronoun=[
"each",
"few",
"many",
"other",
"another",
"anyone",
"some",
"any",
"all",
"such",
"every",
"something",
"none",
"nothing"
"each",
"anything",
"anywhere",
"certain",
"either",
"else",
"elsewhere",
"everybody",
"everyone",
"everything",
"everywhere",
"nobody",
"nowhere",
"several",
"somebody",
"someone",
]

Adjective=[
"able",
"capable",
"far",
"new",
"next",
"important",
"novel",
"similar",
"useful",
"significant",
"recent",
"present",
"related",    # TO THINK
"various",

"interesting",
]

# === conditional noise ===
# 'critical' followed by 'role', etc

# === by-passing ADJective ===
# 'followed', 'proposed', etc

Comparative=[
"sooner",
"earlier",
"later",
"former",
"more",
"less",
"fewer",
"least",
"better",
"worse",
"best",
"worst",
]

Locale=[
"here",
"there",
]

Num=[
"zero",
"one",
"ones",
"two",
"three",
"four",
"five",
"six",
"seven",
"eight",
"nine",
"eighty",
"ninety",
"hundred",
"thousand",
"million",
"first",
"second",
"secondly",
"third",
"forth",
"fifth",
"twice",
]

Reflexive=[
"myself",
"herself",
"himself",
"itself",
"yourself",
"yourselves",
"themselves",
"ourselves",
]

NounOwnership=[
"yours",
"ours",
"theirs",
"others",
"his",
"hers",
"its",
]

# TODO - or better to use 2-grams?
VerConjunctor = [
"using",
"considering",
"leading",
#"according",
]

# some verbs that are never used as noun
# or some of the 3-rd person singular forms that must be verbs
Verbs = [
"having",
"being",
"doing",
"been",
"done",
"analyze", "analyses",
"compute", "computes",
"devise", "devises",
"exploit", "exploits",
"identifies", "identify",
"resolve", "resolves",
"tackle", "tackles",
"consist", "consists",
"implies", "imply",
"employs", "employ",
"reveal", "reveals", # although it can be a noun in the architecture domain
"transform", "transforms",
"exhibit", "exhibits",
"utilise", "utilize", "utilizes",
"understand", "understands",
"simulate", "simulates",
"solve", "solves",
"include", "includes",
"find", "finds",
"confirm", "confirms",
"explore", "explores",
"stabilize", "stabizes",
"perform", "performs",
"ensure", "ensures",
"connect", "connects",
"ascertain", "ascertains",
"alleviate", "alleviates",
"create", "creates",
"compensate", "compensates",
"terminate", "terminates",
"locate", "locates",
"activate", "activates",
"shorten", "shortens",
"retain", "retains",
"prove", "proves",
"justify", "justifies",
"induce", "includes",
"indicate", "indicates",
"exceed", "exceeds",
"apply", "applies",
"accommodate", "accommodates",
"restore", "restores",
"reflect", "reflects",
"introduce", "introduces",
"grow", "grows",
"excite", "excites",
"dominate", "dominates",
"distinguish", "distinguishs",
"choose", "chooses",
"vary", "varies",
"relax", "relaxes",
"infer", "infers",
"expose", "exposes",
"distribute", "distributes",
"depict", "depicts",
"bring", "brings",
"accelerate", "accelerates",
"utilize", "utilizes", "utilises",
"specify", "specifies",
"expand", "expands",
"etch", "etches",
"equalize", "equalizes", "equalises",
"enlarge", "enlarges",
"emphasize", "emphasizes",
"differentiate", "differentiates",
"diagnose", "diagnoses",
"delineate", "delineates",
"become", "becomes",
"withstand", "withstands",
"summarize", "summarizes",
"substantiate", "substantiates",
"refine", "refines",
"reconcile", "reconciles",
"recognize", "recognizes",
"quench", "quenches",
"insulate", "insulates",
"enforce", "enforces",
"decouple", "decouples",
"decode", "decodes",
"alter", "alters",
"acquire", "acquires",
"underlie", "underlies",
"surmount", "surmounts",
"strengthen", "strengthens",
"restrict", "restricts",
"restrain", "restrains",
"regulate", "regulates",
"rectify", "rectifies",
"prolong", "prolongs",
"possess", "possesses",
"obey", "obeys",
"govern", "governs",
"formulate", "formulates",
"extrapolate", "extrapolates",
"erase", "erases",
"divert", "diverts",
"disturb", "disturbs",
"dissipate", "dissipates",
"discover", "discovers",
"diminish", "diminishes",
"deplete", "depletes",
"deflect", "deflects",
"decompose", "decomposes",
"counteract", "counteracts",
"continue", "continues",
"contain", "contains",
"configure", "configures",
"classify", "classifies",
"circumvent", "circumvents",
"automate", "automates",
"assure", "assures",
"assemble", "assembles",
"ameliorate", "ameliorates",
"align", "aligns",
"adapt", "adapts",
"acquaint", "acquaints",
"accumulate", "accumulates",
"accomplish", "accomplishes",
"absorb", "absorbs",
"visualize", "visualizes",
"unravel", "unravels",
"transmit", "transmits",
"translate", "translates",
"tighten", "tightens",
"testify", "testifies",
"supervise", "supervises",
"subtract", "subtracts",
"stimulate", "stimulates",
"sharpen", "sharpens",
"segregate", "segregates",
"resonate", "resonates",
"require", "requires",
"remind", "reminds",
"remain", "remains",
"relieve", "relieves",
"refresh", "refreshs",
"redistribute", "redistributes",
"obstruct", "obstructs",
"receive", "receives",
"pursue", "pursues",
"propose", "proposes",
"promote", "promotes",
"prohibit", "prohibits",
"prescribe", "prescribes",
"prepare", "prepares",
"preclude", "precludes",
"perturb", "perturbs",
"overemphasize", "overemphasizes",
"outweigh", "outweighs",
"outperform", "outperforms",
"optimise", "optimises", "optimizes",
"lessen", "lessens",
"involve", "involves",
"invalidate", "invalidates",
"insure", "insures",
"inspect", "inspects",
"inhibit", "inhibits",
"impose", "imposes",
"impede", "impedes",
"flatten", "flattens",
"expel", "expels",
"execute", "executes",
"exclude", "excludes",
"exaggerate", "exaggerates",
"energize", "energizes",
"endure", "endures",
"encrypt", "encrypts",
"emulate", "emulates",
"emit", "emits",
"distort", "distorts",
"deteriorate", "deteriorates",
"destroy", "destroys",
"deliver", "delivers",
"deform", "deforms",
"defend", "defends",
"curtail", "curtails",
"contribute", "contributes",
"contradict", "contradicts",
"consume", "consumes",
"constrain", "constrains",
"comprise", "comprises",
"clad", "clads",
"certify", "certifies",
"bury", "buries",
"broaden", "broadens",
"attach", "attaches",
"assume", "assumes",
"arrange", "arranges",
"amplify", "amplifies",
"admit", "admits",
]

Abbreviations = [
"", "via", "i", "ii", "iii", "etc", "etc.", "et", "al.", "al", "eg", "eg.",
"ie", "ie.", "w.r.t.", "i.i.f",
]

Punctuations = [",", ":", "'s", '"', '-', '(', ')', '((', '))', '[', ']', '/']

## ----- seen by EXTERNAL FILES ----

HardStop = JieCi + \
           AuxVerb + \
           Adjective + \
           Abbreviations + \
           Adverb + \
           Conjunctive + \
           Comparative + \
           Determiner + \
           DeterminerPersonal + \
           Locale + \
           Modal + \
           Num + \
           NounOwnership + \
           PronounPerson + \
           Pronoun + \
           Questa + \
           Reflexive + \
           VerConjunctor + \
           Verbs + \
           Punctuations

DeterminerGeneral = Determiner + DeterminerPersonal


JudgeAdj = {
"good"  : 1,
"better": 1,
"great" : 1,
"greater":1,
"high"  : 1,
"highly": 1,
"little": 1,
"less"  : 1,
"few"   : 1,
"fewer" : 1,
"much"  : 1,
"more"  : 1,
"bad"   : 1,
"worse" : 1,
"poor"  : 1,
"often" : 1,
"excellent"  : 1,
}
